### PR TITLE
untracked! Update CircleCI config

### PR DESCRIPTION
**Pull request by jrwishart**

### CODE REVIEW

**Comment by jrwishart** [comment]
image

**Comment by jrwishart** [comment]
Put separate test jobs back in that were removed in https://github.com/Displayr/flipMultivariates/pull/33

**Comment by JustinCCYap** [comment]
@jrwishart sorry about this. I should have checked before merging. I didn't expect something like this to occur.

**Review by JustinCCYap — APPROVED** [review]

**Comment by jrwishart** [comment]
> @jrwishart sorry about this. I should have checked before merging. I didn't expect something like this to occur.

No worries. Was weird timing that I made this PR an hour or two before the scatter one merged but you'd done the CircleCI change a couple of months ago for that PR.

**Comment by JustinCCYap** [comment]
I recall I made the change based on Carmen's suggestion to get CI passing, but forgot about it.

**Pull request merged**
